<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrenciesTableSeeder extends Seeder
{
    public function run()
    {

        $data = array(
            ['id' => '1', 'format' => 'AFN', 'value' => 'Afghan Afghani'],
            ['id' => '2', 'format' => 'ALL', 'value' => 'Albanian Lek'],
            ['id' => '3', 'format' => 'DZD', 'value' => 'Algerian Dinar'],
            ['id' => '4', 'format' => 'ADP', 'value' => 'Andorran Peseta'],
            ['id' => '5', 'format' => 'AOA', 'value' => 'Angolan Kwanza'],
            ['id' => '6', 'format' => 'ARA', 'value' => 'Argentine Austral'],
            ['id' => '7', 'format' => 'ARS', 'value' => 'Argentine Peso'],
            ['id' => '8', 'format' => 'AMD', 'value' => 'Armenian Dram'],
            ['id' => '9', 'format' => 'AWG', 'value' => 'Aruban Florin'],
            ['id' => '10', 'format' => 'AUD', 'value' => 'Australian Dollar'],
            ['id' => '11', 'format' => 'ATS', 'value' => 'Austrian Schilling'],
            ['id' => '12', 'format' => 'AZN', 'value' => 'Azerbaijani Manat'],
            ['id' => '13', 'format' => 'BSD', 'value' => 'Bahamian Dollar'],
            ['id' => '14', 'format' => 'BHD', 'value' => 'Bahraini Dinar'],
            ['id' => '15', 'format' => 'BDT', 'value' => 'Bangladeshi Taka'],
            ['id' => '16', 'format' => 'BBD', 'value' => 'Barbadian Dollar'],
            ['id' => '17', 'format' => 'BYN', 'value' => 'Belarusian Ruble'],
            ['id' => '18', 'format' => 'BEF', 'value' => 'Belgian Franc'],
            ['id' => '19', 'format' => 'BZD', 'value' => 'Belize Dollar'],
            ['id' => '20', 'format' => 'BMD', 'value' => 'Bermudan Dollar'],
            ['id' => '21', 'format' => 'BTN', 'value' => 'Bhutanese Ngultrum'],
            ['id' => '22', 'format' => 'BOB', 'value' => 'Bolivian Boliviano'],
            ['id' => '23', 'format' => 'BOV', 'value' => 'Bolivian Mvdol'],
            ['id' => '24', 'format' => 'BOP', 'value' => 'Bolivian Peso'],
            ['id' => '25', 'format' => 'BAM', 'value' => 'Bosnia-Herzegovina Convertible Mark'],
            ['id' => '26', 'format' => 'BWP', 'value' => 'Botswanan Pula'],
            ['id' => '27', 'format' => 'BRL', 'value' => 'Brazilian Real'],
            ['id' => '28', 'format' => 'GBP', 'value' => 'British Pound'],
            ['id' => '29', 'format' => 'BND', 'value' => 'Brunei Dollar'],
            ['id' => '30', 'format' => 'BGN', 'value' => 'Bulgarian Lev'],
            ['id' => '31', 'format' => 'BGM', 'value' => 'Bulgarian Socialist Lev'],
            ['id' => '32', 'format' => 'BUK', 'value' => 'Burmese Kyat'],
            ['id' => '33', 'format' => 'BIF', 'value' => 'Burundian Franc'],
            ['id' => '34', 'format' => 'XPF', 'value' => 'CFP Franc'],
            ['id' => '35', 'format' => 'KHR', 'value' => 'Cambodian Riel'],
            ['id' => '36', 'format' => 'CAD', 'value' => 'Canadian Dollar'],
            ['id' => '37', 'format' => 'CVE', 'value' => 'Cape Verdean Escudo'],
            ['id' => '38', 'format' => 'KYD', 'value' => 'Cayman Islands Dollar'],
            ['id' => '39', 'format' => 'XAF', 'value' => 'Central African CFA Franc'],
            ['id' => '40', 'format' => 'CLE', 'value' => 'Chilean Escudo'],
            ['id' => '41', 'format' => 'CLP', 'value' => 'Chilean Peso'],
            ['id' => '42', 'format' => 'CNY', 'value' => 'Chinese Yuan'],
            ['id' => '43', 'format' => 'COP', 'value' => 'Colombian Peso'],
            ['id' => '44', 'format' => 'COU', 'value' => 'Colombian Real Value Unit'],
            ['id' => '45', 'format' => 'KMF', 'value' => 'Comorian Franc'],
            ['id' => '46', 'format' => 'CDF', 'value' => 'Congolese Franc'],
            ['id' => '47', 'format' => 'CRC', 'value' => 'Costa Rican Colón'],
            ['id' => '48', 'format' => 'HRD', 'value' => 'Croatian Dinar'],
            ['id' => '49', 'format' => 'HRK', 'value' => 'Croatian Kuna'],
            ['id' => '50', 'format' => 'CUC', 'value' => 'Cuban Convertible Peso'],
            ['id' => '51', 'format' => 'CUP', 'value' => 'Cuban Peso'],
            ['id' => '52', 'format' => 'CYP', 'value' => 'Cypriot Pound'],
            ['id' => '53', 'format' => 'CZK', 'value' => 'Czech Koruna'],
            ['id' => '54', 'format' => 'CSK', 'value' => 'Czechoslovak Hard Koruna'],
            ['id' => '55', 'format' => 'DKK', 'value' => 'Danish Krone'],
            ['id' => '56', 'format' => 'DJF', 'value' => 'Djiboutian Franc'],
            ['id' => '57', 'format' => 'DOP', 'value' => 'Dominican Peso'],
            ['id' => '58', 'format' => 'NLG', 'value' => 'Dutch Guilder'],
            ['id' => '59', 'format' => 'XCD', 'value' => 'East Caribbean Dollar'],
            ['id' => '60', 'format' => 'DDM', 'value' => 'East German Mark'],
            ['id' => '61', 'format' => 'ECS', 'value' => 'Ecuadorian Sucre'],
            ['id' => '62', 'format' => 'ECV', 'value' => 'Ecuadorian Unit of Constant Value'],
            ['id' => '63', 'format' => 'EGP', 'value' => 'Egyptian Pound'],
            ['id' => '64', 'format' => 'GQE', 'value' => 'Equatorial Guinean Ekwele'],
            ['id' => '65', 'format' => 'ERN', 'value' => 'Eritrean Nakfa'],
            ['id' => '66', 'format' => 'EEK', 'value' => 'Estonian Kroon'],
            ['id' => '67', 'format' => 'ETB', 'value' => 'Ethiopian Birr'],
            ['id' => '68', 'format' => 'EUR', 'value' => 'Euro'],
            ['id' => '69', 'format' => 'XEU', 'value' => 'European Currency Unit'],
            ['id' => '70', 'format' => 'FKP', 'value' => 'Falkland Islands Pound'],
            ['id' => '71', 'format' => 'FJD', 'value' => 'Fijian Dollar'],
            ['id' => '72', 'format' => 'FIM', 'value' => 'Finnish Markka'],
            ['id' => '73', 'format' => 'FRF', 'value' => 'French Franc'],
            ['id' => '74', 'format' => 'XFO', 'value' => 'French Gold Franc'],
            ['id' => '75', 'format' => 'XFU', 'value' => 'French UIC-Franc'],
            ['id' => '76', 'format' => 'GMD', 'value' => 'Gambian Dalasi'],
            ['id' => '77', 'format' => 'GEK', 'value' => 'Georgian Kupon Larit'],
            ['id' => '78', 'format' => 'GEL', 'value' => 'Georgian Lari'],
            ['id' => '79', 'format' => 'DEM', 'value' => 'German Mark'],
            ['id' => '80', 'format' => 'GHS', 'value' => 'Ghanaian Cedi'],
            ['id' => '81', 'format' => 'GIP', 'value' => 'Gibraltar Pound'],
            ['id' => '82', 'format' => 'GRD', 'value' => 'Greek Drachma'],
            ['id' => '83', 'format' => 'GTQ', 'value' => 'Guatemalan Quetzal'],
            ['id' => '84', 'format' => 'GWP', 'value' => 'Guinea-Bissau Peso'],
            ['id' => '85', 'format' => 'GNF', 'value' => 'Guinean Franc'],
            ['id' => '86', 'format' => 'GNS', 'value' => 'Guinean Syli'],
            ['id' => '87', 'format' => 'GYD', 'value' => 'Guyanaese Dollar'],
            ['id' => '88', 'format' => 'HTG', 'value' => 'Haitian Gourde'],
            ['id' => '89', 'format' => 'HNL', 'value' => 'Honduran Lempira'],
            ['id' => '90', 'format' => 'HKD', 'value' => 'Hong Kong Dollar'],
            ['id' => '91', 'format' => 'HUF', 'value' => 'Hungarian Forint'],
            ['id' => '92', 'format' => 'ISK', 'value' => 'Icelandic Króna'],
            ['id' => '93', 'format' => 'INR', 'value' => 'Indian Rupee'],
            ['id' => '94', 'format' => 'IDR', 'value' => 'Indonesian Rupiah'],
            ['id' => '95', 'format' => 'IRR', 'value' => 'Iranian Rial'],
            ['id' => '96', 'format' => 'IQD', 'value' => 'Iraqi Dinar'],
            ['id' => '97', 'format' => 'IEP', 'value' => 'Irish Pound'],
            ['id' => '98', 'format' => 'ILS', 'value' => 'Israeli New Shekel'],
            ['id' => '99', 'format' => 'ILP', 'value' => 'Israeli Pound'],
            ['id' => '100', 'format' => 'ITL', 'value' => 'Italian Lira'],
            ['id' => '101', 'format' => 'JMD', 'value' => 'Jamaican Dollar'],
            ['id' => '102', 'format' => 'JPY', 'value' => 'Japanese Yen'],
            ['id' => '103', 'format' => 'JOD', 'value' => 'Jordanian Dinar'],
            ['id' => '104', 'format' => 'KZT', 'value' => 'Kazakhstani Tenge'],
            ['id' => '105', 'format' => 'KES', 'value' => 'Kenyan Shilling'],
            ['id' => '106', 'format' => 'KWD', 'value' => 'Kuwaiti Dinar'],
            ['id' => '107', 'format' => 'KGS', 'value' => 'Kyrgystani Som'],
            ['id' => '108', 'format' => 'LAK', 'value' => 'Laotian Kip'],
            ['id' => '109', 'format' => 'LVL', 'value' => 'Latvian Lats'],
            ['id' => '110', 'format' => 'LVR', 'value' => 'Latvian Ruble'],
            ['id' => '111', 'format' => 'LBP', 'value' => 'Lebanese Pound'],
            ['id' => '112', 'format' => 'LSL', 'value' => 'Lesotho Loti'],
            ['id' => '113', 'format' => 'LRD', 'value' => 'Liberian Dollar'],
            ['id' => '114', 'format' => 'LYD', 'value' => 'Libyan Dinar'],
            ['id' => '115', 'format' => 'LTL', 'value' => 'Lithuanian Litas'],
            ['id' => '116', 'format' => 'LTT', 'value' => 'Lithuanian Talonas'],
            ['id' => '117', 'format' => 'LUL', 'value' => 'Luxembourg Financial Franc'],
            ['id' => '118', 'format' => 'LUC', 'value' => 'Luxembourgian Convertible Franc'],
            ['id' => '119', 'format' => 'LUF', 'value' => 'Luxembourgian Franc'],
            ['id' => '120', 'format' => 'MOP', 'value' => 'Macanese Pataca'],
            ['id' => '121', 'format' => 'MKD', 'value' => 'Macedonian Denar'],
            ['id' => '122', 'format' => 'MGA', 'value' => 'Malagasy Ariary'],
            ['id' => '123', 'format' => 'MGF', 'value' => 'Malagasy Franc'],
            ['id' => '124', 'format' => 'MWK', 'value' => 'Malawian Kwacha'],
            ['id' => '125', 'format' => 'MYR', 'value' => 'Malaysian Ringgit'],
            ['id' => '126', 'format' => 'MVR', 'value' => 'Maldivian Rufiyaa'],
            ['id' => '127', 'format' => 'MLF', 'value' => 'Malian Franc'],
            ['id' => '128', 'format' => 'MTL', 'value' => 'Maltese Lira'],
            ['id' => '129', 'format' => 'MTP', 'value' => 'Maltese Pound'],
            ['id' => '130', 'format' => 'MRO', 'value' => 'Mauritanian Ouguiya'],
            ['id' => '131', 'format' => 'MUR', 'value' => 'Mauritian Rupee'],
            ['id' => '132', 'format' => 'MXV', 'value' => 'Mexican Investment Unit'],
            ['id' => '133', 'format' => 'MXN', 'value' => 'Mexican Peso'],
            ['id' => '134', 'format' => 'MDC', 'value' => 'Moldovan Cupon'],
            ['id' => '135', 'format' => 'MDL', 'value' => 'Moldovan Leu'],
            ['id' => '136', 'format' => 'MCF', 'value' => 'Monegasque Franc'],
            ['id' => '137', 'format' => 'MNT', 'value' => 'Mongolian Tugrik'],
            ['id' => '138', 'format' => 'MAD', 'value' => 'Moroccan Dirham'],
            ['id' => '139', 'format' => 'MAF', 'value' => 'Moroccan Franc'],
            ['id' => '140', 'format' => 'MZE', 'value' => 'Mozambican Escudo'],
            ['id' => '141', 'format' => 'MZN', 'value' => 'Mozambican Metical'],
            ['id' => '142', 'format' => 'MMK', 'value' => 'Myanmar Kyat'],
            ['id' => '143', 'format' => 'NAD', 'value' => 'Namibian Dollar'],
            ['id' => '144', 'format' => 'NPR', 'value' => 'Nepalese Rupee'],
            ['id' => '145', 'format' => 'ANG', 'value' => 'Netherlands Antillean Guilder'],
            ['id' => '146', 'format' => 'TWD', 'value' => 'New Taiwan Dollar'],
            ['id' => '147', 'format' => 'NZD', 'value' => 'New Zealand Dollar'],
            ['id' => '148', 'format' => 'NIO', 'value' => 'Nicaraguan Córdoba'],
            ['id' => '149', 'format' => 'NGN', 'value' => 'Nigerian Naira'],
            ['id' => '150', 'format' => 'KPW', 'value' => 'North Korean Won'],
            ['id' => '151', 'format' => 'NOK', 'value' => 'Norwegian Krone'],
            ['id' => '152', 'format' => 'OMR', 'value' => 'Omani Rial'],
            ['id' => '153', 'format' => 'PKR', 'value' => 'Pakistani Rupee'],
            ['id' => '154', 'format' => 'PAB', 'value' => 'Panamanian Balboa'],
            ['id' => '155', 'format' => 'PGK', 'value' => 'Papua New Guinean Kina'],
            ['id' => '156', 'format' => 'PYG', 'value' => 'Paraguayan Guarani'],
            ['id' => '157', 'format' => 'PEI', 'value' => 'Peruvian Inti'],
            ['id' => '158', 'format' => 'PEN', 'value' => 'Peruvian Sol'],
            ['id' => '159', 'format' => 'PHP', 'value' => 'Philippine Peso'],
            ['id' => '160', 'format' => 'PLN', 'value' => 'Polish Zloty'],
            ['id' => '161', 'format' => 'PTE', 'value' => 'Portuguese Escudo'],
            ['id' => '162', 'format' => 'GWE', 'value' => 'Portuguese Guinea Escudo'],
            ['id' => '163', 'format' => 'QAR', 'value' => 'Qatari Rial'],
            ['id' => '164', 'format' => 'XRE', 'value' => 'RINET Funds'],
            ['id' => '165', 'format' => 'RHD', 'value' => 'Rhodesian Dollar'],
            ['id' => '166', 'format' => 'RON', 'value' => 'Romanian Leu'],
            ['id' => '167', 'format' => 'RUB', 'value' => 'Russian Ruble'],
            ['id' => '168', 'format' => 'RWF', 'value' => 'Rwandan Franc'],
            ['id' => '169', 'format' => 'SVC', 'value' => 'Salvadoran Colón'],
            ['id' => '170', 'format' => 'WST', 'value' => 'Samoan Tala'],
            ['id' => '171', 'format' => 'SAR', 'value' => 'Saudi Riyal'],
            ['id' => '172', 'format' => 'RSD', 'value' => 'Serbian Dinar'],
            ['id' => '173', 'format' => 'SCR', 'value' => 'Seychellois Rupee'],
            ['id' => '174', 'format' => 'SLL', 'value' => 'Sierra Leonean Leone'],
            ['id' => '175', 'format' => 'SGD', 'value' => 'Singapore Dollar'],
            ['id' => '176', 'format' => 'SKK', 'value' => 'Slovak Koruna'],
            ['id' => '177', 'format' => 'SIT', 'value' => 'Slovenian Tolar'],
            ['id' => '178', 'format' => 'SBD', 'value' => 'Solomon Islands Dollar'],
            ['id' => '179', 'format' => 'SOS', 'value' => 'Somali Shilling'],
            ['id' => '180', 'format' => 'ZAR', 'value' => 'South African Rand'],
            ['id' => '181', 'format' => 'KRW', 'value' => 'South Korean Won'],
            ['id' => '182', 'format' => 'SSP', 'value' => 'South Sudanese Pound'],
            ['id' => '183', 'format' => 'SUR', 'value' => 'Soviet Rouble'],
            ['id' => '184', 'format' => 'ESP', 'value' => 'Spanish Peseta'],
            ['id' => '185', 'format' => 'LKR', 'value' => 'Sri Lankan Rupee'],
            ['id' => '186', 'format' => 'SHP', 'value' => 'St. Helena Pound'],
            ['id' => '187', 'format' => 'SDG', 'value' => 'Sudanese Pound'],
            ['id' => '188', 'format' => 'SRD', 'value' => 'Surinamese Dollar'],
            ['id' => '189', 'format' => 'SRG', 'value' => 'Surinamese Guilder'],
            ['id' => '190', 'format' => 'SZL', 'value' => 'Swazi Lilangeni'],
            ['id' => '191', 'format' => 'SEK', 'value' => 'Swedish Krona'],
            ['id' => '192', 'format' => 'CHF', 'value' => 'Swiss Franc'],
            ['id' => '193', 'format' => 'SYP', 'value' => 'Syrian Pound'],
            ['id' => '194', 'format' => 'STD', 'value' => 'São Tomé & Príncipe Dobra'],
            ['id' => '195', 'format' => 'TJR', 'value' => 'Tajikistani Ruble'],
            ['id' => '196', 'format' => 'TJS', 'value' => 'Tajikistani Somoni'],
            ['id' => '197', 'format' => 'TZS', 'value' => 'Tanzanian Shilling'],
            ['id' => '198', 'format' => 'THB', 'value' => 'Thai Baht'],
            ['id' => '199', 'format' => 'TPE', 'value' => 'Timorese Escudo'],
            ['id' => '200', 'format' => 'TOP', 'value' => 'Tongan Paʻanga'],
            ['id' => '201', 'format' => 'TTD', 'value' => 'Trinidad & Tobago Dollar'],
            ['id' => '202', 'format' => 'TND', 'value' => 'Tunisian Dinar'],
            ['id' => '203', 'format' => 'TRY', 'value' => 'Turkish Lira'],
            ['id' => '204', 'format' => 'TMT', 'value' => 'Turkmenistani Manat'],
            ['id' => '205', 'format' => 'USD', 'value' => 'US Dollar'],
            ['id' => '206', 'format' => 'UGX', 'value' => 'Ugandan Shilling'],
            ['id' => '207', 'format' => 'UAH', 'value' => 'Ukrainian Hryvnia'],
            ['id' => '208', 'format' => 'UAK', 'value' => 'Ukrainian Karbovanets'],
            ['id' => '209', 'format' => 'AED', 'value' => 'United Arab Emirates Dirham'],
            ['id' => '210', 'format' => 'UYU', 'value' => 'Uruguayan Peso'],
            ['id' => '211', 'format' => 'UZS', 'value' => 'Uzbekistani Som'],
            ['id' => '212', 'format' => 'VUV', 'value' => 'Vanuatu Vatu'],
            ['id' => '213', 'format' => 'VEF', 'value' => 'Venezuelan Bolívar'],
            ['id' => '214', 'format' => 'VND', 'value' => 'Vietnamese Dong'],
            ['id' => '215', 'format' => 'CHE', 'value' => 'WIR Euro'],
            ['id' => '216', 'format' => 'CHW', 'value' => 'WIR Franc'],
            ['id' => '217', 'format' => 'XOF', 'value' => 'West African CFA Franc'],
            ['id' => '218', 'format' => 'YDD', 'value' => 'Yemeni Dinar'],
            ['id' => '219', 'format' => 'YER', 'value' => 'Yemeni Rial'],
            ['id' => '220', 'format' => 'ZMW', 'value' => 'Zambian Kwacha']

        );

        /* Truncate all the data before populating*/
        if (DB::table('currencies')->get()->count() > 0) {
            DB::table('currencies')->truncate();
        }

        DB::table('currencies')->insert($data);
    }
}
